runtime: nodejs
env: flex

handlers:
- url: /(.*\.(html|css|js|jpg|png|ico|svg}))$
  static_files: build/\1
  upload: build/(.*\.(html|css|js|jpg|png|ico|svg))

- url: /.*
  static_files: build/index.html
  upload: build/index.html

env_variables:
  MAP_API: "AIzaSyDKNw45VT92V-NWTQokK03QedFFJxVYono&callback=initMap"