runtime: nodejs
env: flex

handlers:
- url: /(.*\.(html|css|jpg|png|ico}))$
  static_files: build/\1
  upload: build/(.*\.(html|css|js|jpg|png|ico))


- url: /.*
  static_files: public/index.html
  upload: public/index.html