runtime: nodejs
env: flex

handlers:
- url: /(.*\.(html|css|js))
  static_files: build/\1
  upload: build/(.*\.(html|css|js))


- url: /.*
  static_files: public/index.html
  upload: public/index.html